//Localhost
//get all record
### GET wmemberlist
GET http://localhost:8080/wmemberlist HTTP/1.1

### GET wmemberlist
GET http://localhost:8080/wmemberlist/63364a0ee193daf7b271aac8 


###PUT wmemberlist
PUT http://localhost:8080/wmemberlist/63364a0ee193daf7b271aac7 HTTP/1.1
Content-Type: application/json

	{
		"firstname": "Christy",
		"lastName": "Carl",
		"email": "cristy@test.com",
		"phoneNumber": "213-1233-1232",
		"streetAddress": "123 Bolling Street #310, Seattle, WA 9800",
		"birthday": "1963-01-04",
		"placeOfbirth": "Seattle"
	}


//Render- Ward list
### 
GET https://cse341-personal.onrender.com/wmemberlist HTTP/1.1

### 
GET https://cse341-personal.onrender.com/wmemberlist//633640d4e193daf7b271aaa4 HTTP/1.1

###
POST https://cse341-personal.onrender.com/wmemberlist/ HTTP/1.1
Content-Type: application/json

 {
	 	"firstname": "Erika",
	 	"lastName": "Watanabe",
	 	"email": "erikaw@test.com",
	 	"phoneNumber": "555-5555-5555",
	 	"streetAddress": "123 apple Street #1012, Tokyo, JP 2222",
	 	"birthday": "1991-12-10",
	 	"placeOfbirth": "Tokyo"
	 }

###
PUT http://localhost:8080/wmemberlist/63364a0ee193daf7b271aac7 HTTP/1.1
Content-Type: application/application/json

{
    "firstname": "Christy",
	"lastName": "Allred",
	"email": "cristy@test.com",
	"phoneNumber": "213-1233-1232",
 	"streetAddress": "123 Bolling Street #310, Seattle, WA 9800",
 	"birthday": "1963-01-04",
	"placeOfbirth": "Seattle"
}

### 
DELETE  http://localhost:8080/wmemberlist/63364a0ee193daf7b271aac8 HTTP/1.1


//Render- User

### 
GET https://cse341-personal.onrender.com/user HTTP/1.1
