//Localhost
//get all record
### GET 
http://localhost:8080/wmemberlist HTTP/1.1


//Render
### GET 
https://cse341-personal.onrender.com/wmemberlist HTTP/1.1

### GET 
https://cse341-personal.onrender.com/wmemberlist//633640d4e193daf7b271aaa4 HTTP/1.1